Branch for the front page
Zelalem1222/Personal-Portfolio pull request #1
Opened 2022-04-25 12:52 UTC by Zelalem1222

This is mobile-size portfolio designed with HTML and CSS. This portfolio also has HTML and CSS linter.

2022-04-25 14:05 UTC, AnselemOdims requested changes
### Hi @Zelalem1222 , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please make your pull request summary more descriptive
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-25 14:05 UTC, AnselemOdims commented on index.html
> +    </nav>
- [ ] Kindly ensure that the navbar is enclosed inside a `header` tag for semantic purposes

2022-04-25 14:05 UTC, AnselemOdims commented on index.html
> +            <h3>My Logo</h3>
- [ ] Please kindly make sure that the logo is wrapped inside an anchor `a` tag instead of the `h3`

2022-04-25 14:05 UTC, AnselemOdims commented on index.html
> +    <header >
- [ ] Please kindly use a `section tag here instead of `header` tag for semantic purposes

2022-04-25 14:05 UTC, AnselemOdims commented on index.html
> +                <img class="vector7" src="images/vector7.svg" alt="">
- [ ] Please ensure that the list of icons uses a `ul` tag to group them, and `li` per icon; each icon has a link (a tag)
- [ ] Please kindly use the icons as specified in the design. You can download them by exporting

2022-04-25 14:05 UTC, AnselemOdims commented on index.html
> +    </div>
- [ ] Please ensure to include background images by using the `background-img` CSS property. Kindly remove these `img` tags and include the background image from CSS

2022-04-25 14:05 UTC, AnselemOdims commented on index.html
> +                <img class="vector6" src="images/vector6.svg" alt="">
- [ ] At the moment, there is horizontal scroll which does not give a good user experience. Please kindly remove it

2022-04-25 17:07 UTC, keroloussamy requested changes
Hi @Zelalem1222, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

![](https://camo.githubusercontent.com/6ac905aa3a075ef45de55758c20c6e6efb1dfdbbb0d9fd03d4718d26c5c96cde/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4a713832345239334a734c775a436169534c2f67697068792e676966)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-25 17:07 UTC, keroloussamy commented on index.html
> +    </div>
- [ ] Kindly as asked by the previous reviewer, Please ensure to include background images by using the `background-img` CSS property. You can download all these images in one image from the Figma design and set it using `background-img` CSS property.

2022-04-26 09:26 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @Zelalem1222,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- Github flow is used correctly. ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-26 09:28 UTC, merged